INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (1, 'Uzumaki Naruto', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (2, 'Hatake Kakashi', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (3, 'Haruno Sakura', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (4, 'Uchiha Sasuke', 'Missing-nin')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (5, 'Gaara', 'Sunagakure')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (6, 'Killer Bee', 'Kumogakure')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (7, 'Jiraya', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (8, 'Namikaze Minato', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (9, 'Uchiha Madara', 'Missing-nin')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (10, 'Senju Hashirama', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (11, 'Might Guy', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (12, 'Hyuga Neji', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (13, 'Rock Lee', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (14, 'Uchiha Obito', 'Missing-nin')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (15, 'Kurama', 'Tailed Beast')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (16, 'Uzumaki Kushina', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (17, 'Nara Shikamaru', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (18, 'Sarutobi Hiruzen', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (19, 'Tsunade', 'Konoha')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (20, 'Orochimaru', 'Missing-nin')
INSERT INTO PERSON("ID", "NAME", "DESCRIPTION") VALUES (21, 'Uchicha Itachi', 'Missing-nin')
